
services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
